wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.12.21
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.8.12
    start_time: 1666946219
    t:
      1:
      - 55
      2:
      - 55
      4: 3.8.12
      5: 0.12.21
      8:
      - 3
      - 5
data_params:
  desc: null
  value:
    data_path: D:/LaureaMagistrale/Tesi Magistrale/MICCAI Data/MICCAI_BraTS_2018_Data_Training
    dataset: brats2018
exp_params:
  desc: null
  value:
    lr: 0.08503704635642793
sweep_params:
  desc: null
  value:
    ntrials: 1
    project: MICCAI 2018 Medical Image Segmentation
trainer_params:
  desc: null
  value:
    accelerator: gpu
    devices: 1
    limit_val_batches: 0
    max_steps: 100
    max_time: 00:00:10:00
    num_sanity_val_steps: 0
